### ISSUE TITLE
maybe it's better provide the dataset of the book

### ISSUE THREAD

**Issue by fengdy** [dataPipelineAU/LearningDataMiningWithPython#1]
Thanks for your sharing, maybe it is better  with dataset  used by the book provided, i find it hard for me to get the dataset of chapter 6

**Comment by robertlayton** [comment]
Hi fengdy. Unfortunately I can't directly provide the datasets, especially from twitter (their terms of service explicitly prohibit it). I have provided the tweet ids of the dataset I've provided -- https://github.com/dataPipelineAU/LearningDataMiningWithPython/blob/master/LearningDataMiningBook/Chapter%206/replicable_dataset.json

What is your error when trying to get the dataset?

**Comment by fengdy** [comment]
I use the ch6_get_twitter with my own twitter information,  it raise a error:
'httplib.BadStatusLine: ''  '  in the line:
search_results = t.search.tweets(q="python", count=100)['statuses']

**Comment by robertlayton** [comment]
Can you try printing the results of just:

`t.search.tweets(q="python", count=100)`

**Comment by fengdy** [comment]
yea, it's the same error:  httplib.BadStatusLine: ''

**Comment by robertlayton** [comment]
Looks like the reply coming back from Twitter isn't a valid response (or at least, not what httplib expected to be parsing). Can you download stuff using the `requests` library?

Try:

``` python
import requests
response = requests.get("https://twitter.com")
print(response.text[:100])
```

If that looks like HTML, I'm not sure -- this would be a question for the authors of the twitter library.

**Comment by robertlayton** [comment]
@fengdy How did you go?

**Comment by edthedev** [comment]
@fengdy A common problem users of the Twitter API can encounter is sending requests to it too quickly in a row. If you do so, you will start receiving HTML in the response object with a message asking you to slow down the rate of your requests. If you find this to be the case, adding the line:

sleep(1000)

to your for loop will help.

**Comment by robertlayton** [comment]
I'm closing this issues as it is unrelated to the code.
