### ISSUE TITLE
How it works in Naive Bayes

### ISSUE THREAD

**Issue by javabean68** [dataPipelineAU/LearningDataMiningWithPython#11]
Hi,

thank you for your book: nice indeed. I'm reading it on Safari. I cannot understand something. In Paragraph 'How it Works'  in Chapter 'Social Media Insight using Naive Bayes' shouldn't it be for the sample  [0, 0, 0, 1] P(D|C=0) = P(D1|C=0) x P(D2|C=0) x P(D3|C=0) x P(D4|C=0) = **0.7** x 0.6 x 0.6 x 0.7 instead of P(D|C=0) = P(D1|C=0) x P(D2|C=0) x P(D3|C=0) x P(D4|C=0) = **0.3** x 0.6 x 0.6 x 0.7? For Class 0 we have : [0.3, 0.4, 0.4, 0.7] and it is said 'The second and third values are 0.6, because the value of that feature in the sample was 0.' The first value is 0 as well...

Thank you for your help in advance
Bye
Fabio

**Comment by robertlayton** [comment]
Yes you are right!
