### ISSUE TITLE
getdata.py fail to download books

### ISSUE THREAD

**Issue by dlewin** [dataPipelineAU/LearningDataMiningWithPython#3]
while the the 1st book for burton with id **4657 *_was correct, the next one with *_2400** failed : after looking into the gutenberg path, it seems that this url not pointing to the book. Got some issues with some other links too.
I Got good results with :url_base= "http://eremita.di.uminho.pt"

**Comment by robertlayton** [comment]
Thanks for letting me know. I'm not able to get the files with that URL though -- can you please confirm it?

**Comment by dlewin** [comment]
I have been able with different files : if necessary, tell me : I would try again

**Comment by robertlayton** [comment]
Could you please? No need to run through all the books -- if you get just the first five, that's probably good enough (and includes an ID that we know doesn't work for some URLs)
