### ISSUE TITLE
Label Json format in ch6_label_twitter

### ISSUE THREAD

**Issue by shkabko** [dataPipelineAU/LearningDataMiningWithPython#7]
I have created json files with tweets, and I followed your tutorial in a similar to https://github.com/giswqs/Learning-Python/blob/master/Learning-Data-Mining-with-Python/Chapter%206/ch6_label_twitter.ipynb

way. However, I can not get 
<IPython.core.display.Javascript at 0x10562f438> object in  [119] and I get an errors
`Javascript error adding output!
ReferenceError: load_next_tweet is not defined
See your browser Javascript console for more details.`
after I run [120]

List of what I have installed
alabaster==0.7.9
anaconda-clean==1.0
anaconda-client==1.5.1
anaconda-navigator==1.2.3
argcomplete==1.0.0
astroid==1.4.7
astropy==1.0.4
Babel==2.3.4
backports-abc==0.4
backports.shutil-get-terminal-size==1.0.0
backports.ssl-match-hostname==3.4.0.2
beautifulsoup4==4.5.1
bitarray==0.8.1
blaze==0.10.1
bokeh==0.12.2
boto==2.42.0
Bottleneck==1.0.0
cdecimal==2.3
cffi==1.7.0
chest==0.2.3
click==6.6
cloudpickle==0.2.1
clyent==1.2.2
colorama==0.3.7
configobj==5.0.6
configparser==3.5.0
contextlib2==0.5.3
cryptography==1.5
cycler==0.10.0
Cython==0.24.1
cytoolz==0.8.0
dask==0.11.0
datashape==0.5.2
decorator==4.0.10
dill==0.2.5
docutils==0.12
dynd==0.7.3.dev1
enum34==1.1.6
et-xmlfile==1.0.1
fastcache==1.0.2
filelock==2.0.6
Flask==0.11.1
Flask-Cors==2.1.2
funcsigs==1.0.2
functools32==3.2.3.post2
futures==3.0.5
gevent==1.1.2
greenlet==0.4.10
grin==1.2.1
h5py==2.5.0
HeapDict==1.0.0
idna==2.1
imagesize==0.7.1
ipaddress==1.0.16
ipykernel==4.5.0
ipython==5.1.0
ipython-genutils==0.1.0
ipywidgets==5.2.2
itsdangerous==0.24
jdcal==1.2
jedi==0.9.0
Jinja2==2.8
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.4.0
jupyter-console==5.0.0
jupyter-core==4.2.0
Keras==1.1.0
lazy-object-proxy==1.2.1
llvmlite==0.13.0
llvmpy==0.12.7
locket==0.2.0
lxml==3.6.4
MarkupSafe==0.23
matplotlib==1.4.3
mistune==0.7.3
mock==2.0.0
mpmath==0.19
multipledispatch==0.4.8
nb-anacondacloud==1.2.0
nb-conda==2.0.0
nb-conda-kernels==2.0.0
nbconvert==4.2.0
nbformat==4.1.0
nbpresent==3.0.2
networkx==1.11
nltk==3.2.1
nose==1.3.7
notebook==4.2.3
numba==0.15.1
numexpr==2.4.4
numpy==1.11.2
odo==0.5.0
openpyxl==2.3.2
pandas==0.17.1
partd==0.3.6
path.py==0.0.0
pathlib2==2.1.0
patsy==0.4.1
pbr==1.10.0
pep8==1.7.0
pexpect==4.0.1
pickleshare==0.7.4
Pillow==3.3.1
pkginfo==1.3.2
ply==3.9
prompt-toolkit==1.0.3
protobuf==3.1.0
psutil==4.3.1
ptyprocess==0.5.1
py==1.4.31
pyaml==16.9.0
pyasn1==0.1.9
pycairo==1.10.0
pycosat==0.6.1
pycparser==2.14
pycrypto==2.6.1
pycurl==7.43.0
pyflakes==1.3.0
Pygments==2.1.3
pylint==1.5.4
pyOpenSSL==16.0.0
pyparsing==2.0.3
pytest==2.9.2
python-dateutil==2.5.3
pytz==2016.6.1
PyYAML==3.12
pyzmq==15.4.0
QtAwesome==0.3.3
qtconsole==4.2.1
QtPy==1.1.2
redis==2.10.5
requests==2.11.1
rope==0.9.4
scikit-image==0.11.3
scikit-learn==0.19.dev0
scipy==0.17.1
simplegeneric==0.8.1
simplejson==3.10.0
singledispatch==3.4.0.3
six==1.10.0
snowballstemmer==1.2.1
sockjs-tornado==1.0.3
Sphinx==1.4.6
spyder==3.0.1
SQLAlchemy==1.0.13
statsmodels==0.6.1
sympy==1.0
tables==3.2.2
tensorflow==0.11.0rc0
terminado==0.6
Theano==0.8.2
toolz==0.8.0
tornado==4.4.1
traitlets==4.3.0
twitter==1.17.1
unicodecsv==0.14.1
wcwidth==0.1.7
Werkzeug==0.11.11
widgetsnbextension==1.2.6
wrapt==1.10.6
xgboost==0.40
xlrd==1.0.0
XlsxWriter==0.9.3
xlwt==1.1.2

Browser chrome on ubuntu 14.04 ( but the same issue appear under Win10)

**Comment by shkabko** [comment]
with a new version 

https://github.com/dataPipelineAU/LearningDataMiningWithPython/blob/master/LearningDataMiningBook/Chapter%206/ch6_label_twitter.ipynb

tweets are not loaded, so it results in empty line 
`Instructions: Click in text box. Enter a 1 if the tweet is relevant, enter 0 otherwise.
Tweet:`

and labeling is unresponsive

**Comment by robertlayton** [comment]
Hi, this is fixed in this repo's version. See here: https://github.com/dataPipelineAU/LearningDataMiningWithPython/blob/master/LearningDataMiningBook/Chapter%206/ch6_label_twitter.ipynb

**Comment by shkabko** [comment]
I found, thanks, labeling is working, but tweet_text is not visible

**Comment by robertlayton** [comment]
@shkabko sorry, my notifications on github weren't working. Did you get your issue resolved?

**Comment by corozon** [comment]
I have created json files with tweets and complete html/javascript codes ,but when enter 0/1 I got an error:

`Couldn't process kernel message TypeError: Cannot read property 'text/plain' of undefined`
what can i do for this?
thanks

**Comment by robertlayton** [comment]
@corozon you will need to provide some more information than that, i.e. code and software version numbers.

**Comment by corozon** [comment]
@robertlayton  Thanks for the quick reply!
my codes:
```
%%html
<div name="tweetbox">
Instructions: Click in textbox. Enter a 1 if the tweet is
relevant, enter 0 otherwise.<br>
Tweet: <div id="tweet_text" value="text"></div><br>
<input type=text id="capture"></input><br>
</div>

<script>
function set_lable(lable){
    var kernel = IPython.notebook.kernel;
    kernel.execute("lables.append(" + lable + ")");
    load_next_tweet();
}
function load_next_tweet(){
    var code_input = "get_next_tweet()";
    var kernel = IPython.notebook.kernel;
    var callbacks = { 'iopub':{'output' : handle_output}};
    kernel.execute(code_input,callbacks,{silent:false});
}
function handle_output(out){
    var res = out.content.data["text/plain"];
    $("div#tweet_text").html(res);
}
$("input#capture").keypress(function(e) {
if(e.which == 48) {
    set_lable(0);
    $("input#capture").val("");
}else if (e.which == 49){
    set_lable(1);
    $("input#capture").val("");
}
});
load_next_tweet();
</script>
```
the error:
![image](https://user-images.githubusercontent.com/24630214/40429594-a2db0630-5ed5-11e8-9145-e23706a0b45f.png)
and my ipython and kernel version :（Is this what you need？）
![image](https://user-images.githubusercontent.com/24630214/40429925-68fc2998-5ed6-11e8-8ca3-5bf02c886bc5.png)

**Comment by corozon** [comment]
`
%%html
<div name="tweetbox">
Instructions: Click in textbox. Enter a 1 if the tweet is
relevant, enter 0 otherwise.<br>
Tweet: <div id="tweet_text" value="text"></div><br>
<input type=text id="capture"></input><br>
</div>

<script>
function set_lable(lable){
    var kernel = IPython.notebook.kernel;
    kernel.execute("lables.append(" + lable + ")");
    load_next_tweet();
}
function load_next_tweet(){
    var code_input = "get_next_tweet()";
    var kernel = IPython.notebook.kernel;
    var callbacks = { 'iopub':{'output' : handle_output}};
    kernel.execute(code_input,callbacks,{silent:false});
}
function handle_output(out){
    var res = out.content.data["text/plain"];
    $("div#tweet_text").html(res);
}
$("input#capture").keypress(function(e) {
if(e.which == 48) {
    set_lable(0);
    $("input#capture").val("");
}else if (e.which == 49){
    set_lable(1);
    $("input#capture").val("");
}
});
load_next_tweet();
</script>
`

**Comment by corozon** [comment]
'''
%%html
<div name="tweetbox">
Instructions: Click in textbox. Enter a 1 if the tweet is
relevant, enter 0 otherwise.<br>
Tweet: <div id="tweet_text" value="text"></div><br>
<input type=text id="capture"></input><br>
</div>

<script>
function set_lable(lable){
    var kernel = IPython.notebook.kernel;
    kernel.execute("lables.append(" + lable + ")");
    load_next_tweet();
}
function load_next_tweet(){
    var code_input = "get_next_tweet()";
    var kernel = IPython.notebook.kernel;
    var callbacks = { 'iopub':{'output' : handle_output}};
    kernel.execute(code_input,callbacks,{silent:false});
}
function handle_output(out){
    var res = out.content.data["text/plain"];
    $("div#tweet_text").html(res);
}
$("input#capture").keypress(function(e) {
if(e.which == 48) {
    set_lable(0);
    $("input#capture").val("");
}else if (e.which == 49){
    set_lable(1);
    $("input#capture").val("");
}
});
load_next_tweet();
</script>
'''

**Comment by corozon** [comment]
@robertlayton 
my code
```
%%html
<div name="tweetbox">
Instructions: Click in textbox. Enter a 1 if the tweet is
relevant, enter 0 otherwise.<br>
Tweet: <div id="tweet_text" value="text"></div><br>
<input type=text id="capture"></input><br>
</div>

<script>
function set_lable(lable){
    var kernel = IPython.notebook.kernel;
    kernel.execute("lables.append(" + lable + ")");
    load_next_tweet();
}
function load_next_tweet(){
    var code_input = "get_next_tweet()";
    var kernel = IPython.notebook.kernel;
    var callbacks = { 'iopub':{'output' : handle_output}};
    kernel.execute(code_input,callbacks,{silent:false});
}
function handle_output(out){
    var res = out.content.data["text/plain"];
    $("div#tweet_text").html(res);
}
$("input#capture").keypress(function(e) {
if(e.which == 48) {
    set_lable(0);
    $("input#capture").val("");
}else if (e.which == 49){
    set_lable(1);
    $("input#capture").val("");
}
});
load_next_tweet();
</script>
```

**Comment by corozon** [comment]
ok,after i change my code like you,it work.
and thank u a lot!

**Comment by robertlayton** [comment]
Glad to hear!
